name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      #  Backend
      - name: Install Backend Dependencies
        run: npm install
        working-directory: server

      - name: Test Backend
        run: npm test
        working-directory: server

      #  Frontend
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: frontend

      - name: Build Frontend
        run: npm run build
        working-directory: frontend